name: My First Workflow

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check our reporsitory
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: action/setup-node@v3
        with: 
          node-version: 18

      - name: Print a message
        run: echo "Hello, World!!" 
